spring:
  application:
    name: HappyPaws
  datasource:
    url: jdbc:mysql://localhost:3306/happy_paws
    username: spring_server
    password: server_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: true
server:
  error:
    include-message: always
#spring.jpa.hibernate.ddl-auto=update