spring:
  application:
    name: HappyPaws
  datasource:
    url: jdbc:mysql://kcpgm0ka8vudfq76.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/paej8obdvj21mywz
    username: k6eriaa4w5h85s4k
    password: d7ar510t4irgaz8q
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: true
server:
  error:
    include-message: always